CREATE TABLE ALUMNOS (DNI INT(9), NOMBRE VARCHAR(20), APELLIDO1 VARCHAR(20), APELLIDO2 VARCHAR(20), GENERO VARCHAR(4), DIRECCION VARCHAR(100), TELEFONO VARCHAR(9), EMAIL VARCHAR(40), FECHA_NACIMIENTO DATE, FECHA_PRIM_MATRICULA DATE, CPRO INT(2), CMUN INT(5));
CREATE TABLE ASIGNATURAS (CODIGO INT(3), NOMBRE VARCHAR(50), DEPARTAMENTO INT(3), CREDITOS DECIMAL(3,1), TEORICOS DECIMAL(3,1), PRACTICOS DECIMAL(3,1), CARACTER VARCHAR(2), CURSO INT(1), WEB VARCHAR(30), COD_MATERIA INT(2));
CREATE TABLE CORREQUISITOS (ASIGNATURA INT(3), CORREQUISITO INT(3));
CREATE TABLE DEPARTAMENTOS (CODIGO INT(3), NOMBRE VARCHAR(40), DIRECCION VARCHAR(30), TELEFONO VARCHAR(9), WEB VARCHAR(30), FECHA_CREACION DATE);
CREATE TABLE IMPARTIR (PROFESOR VARCHAR(20), ASIGNATURA INT(3), GRUPO VARCHAR(1), CURSO VARCHAR(5), CARGA_CREDITOS DECIMAL(3,1));
CREATE TABLE INVESTIGADORES (ID_PROFESOR VARCHAR(20), TRAMOS INT(2));
CREATE TABLE MATERIAS (CODIGO INT(2), NOMBRE VARCHAR(40), DESCRIPCION VARCHAR(200));
CREATE TABLE MATRICULAR (ALUMNO INT(9), ASIGNATURA INT(3), GRUPO VARCHAR(1), CURSO VARCHAR(5), CALIFICACION VARCHAR(2) DEFAULT 'NP');
CREATE TABLE MUNICIPIO (CPRO INT(2), CMUN INT(5), NOMBRE VARCHAR(50), HOMBRES INT, MUJERES INT);
CREATE TABLE PRERREQUISITOS (ASIGNATURA INT(3), PRERREQUISITO INT(3));
CREATE TABLE PROFESORES (ID VARCHAR(20), NOMBRE VARCHAR(20), APELLIDO1 VARCHAR(20), APELLIDO2 VARCHAR(20), DEPARTAMENTO INT(3), TELEFONO VARCHAR(4), EMAIL VARCHAR(100), DESPACHO VARCHAR(10), FECHA_NACIMIENTO DATE, ANTIGUEDAD DATE, DIRECTOR_TESIS VARCHAR(20));
CREATE TABLE PROVINCIA (CODIGO INT(2), NOMBRE VARCHAR(30)); 

ALTER TABLE ALUMNOS ADD CONSTRAINT ALUMNOS_PK PRIMARY KEY (DNI);
ALTER TABLE ALUMNOS MODIFY NOMBRE VARCHAR(20) NOT NULL; 
ALTER TABLE ALUMNOS MODIFY FECHA_PRIM_MATRICULA DATE NOT NULL;

ALTER TABLE IMPARTIR ADD CONSTRAINT IMPARTIR_PK PRIMARY KEY (PROFESOR, ASIGNATURA, GRUPO, CURSO);

ALTER TABLE MATRICULAR ADD CONSTRAINT MATRICULAR_PK PRIMARY KEY (ALUMNO, ASIGNATURA, GRUPO, CURSO);

ALTER TABLE MUNICIPIO ADD CONSTRAINT MUNICIPIO_PK PRIMARY KEY (CPRO, CMUN);
ALTER TABLE MUNICIPIO MODIFY CPRO INT(2) NOT NULL;
ALTER TABLE MUNICIPIO MODIFY CMUN INT(5) NOT NULL;
ALTER TABLE MUNICIPIO MODIFY NOMBRE VARCHAR(50) NOT NULL;

ALTER TABLE INVESTIGADORES ADD CONSTRAINT DIRECTORES_PK PRIMARY KEY (ID_PROFESOR);

ALTER TABLE DEPARTAMENTOS ADD CONSTRAINT DEPARTAMENTOS_PK PRIMARY KEY (CODIGO);
ALTER TABLE DEPARTAMENTOS MODIFY NOMBRE VARCHAR(40) NOT NULL;

ALTER TABLE CORREQUISITOS ADD CONSTRAINT CORREQUISITOS_PK PRIMARY KEY (ASIGNATURA, CORREQUISITO);

ALTER TABLE MATERIAS ADD CONSTRAINT MATERIAS_PK PRIMARY KEY (CODIGO);
ALTER TABLE MATERIAS MODIFY NOMBRE VARCHAR(40) NOT NULL;

ALTER TABLE PROFESORES ADD CONSTRAINT PROFESORES_PK PRIMARY KEY (ID);
ALTER TABLE PROFESORES MODIFY NOMBRE VARCHAR(20) NOT NULL;
ALTER TABLE PROFESORES MODIFY APELLIDO1 VARCHAR(20) NOT NULL;
ALTER TABLE PROFESORES MODIFY DEPARTAMENTO INT(3) NOT NULL;

ALTER TABLE PRERREQUISITOS ADD CONSTRAINT PRERREQUISITOS_PK PRIMARY KEY (ASIGNATURA, PRERREQUISITO);

ALTER TABLE ASIGNATURAS ADD CONSTRAINT ASIGNATURAS_PK PRIMARY KEY (CODIGO);
ALTER TABLE ASIGNATURAS MODIFY NOMBRE VARCHAR(50) NOT NULL;

ALTER TABLE PROVINCIA ADD CONSTRAINT PROVINCIA_PK PRIMARY KEY (CODIGO);
ALTER TABLE PROVINCIA MODIFY CODIGO INT(2) NOT NULL;
ALTER TABLE PROVINCIA MODIFY NOMBRE VARCHAR(30) NOT NULL;