ALTER TABLE ALUMNOS ADD CONSTRAINT ALUMNOS_FK1 FOREIGN KEY (CPRO, CMUN) REFERENCES MUNICIPIO (CPRO, CMUN);

ALTER TABLE ASIGNATURAS ADD CONSTRAINT FK_ASIG_DEPAR FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTOS (CODIGO);
ALTER TABLE ASIGNATURAS ADD CONSTRAINT FK_ASIG_MATERIA FOREIGN KEY (COD_MATERIA) REFERENCES MATERIAS (CODIGO);

ALTER TABLE CORREQUISITOS ADD CONSTRAINT FK_CO_ASIG FOREIGN KEY (ASIGNATURA) REFERENCES ASIGNATURAS (CODIGO); 
ALTER TABLE CORREQUISITOS ADD CONSTRAINT FK_CO_ASIG_CO FOREIGN KEY (CORREQUISITO) REFERENCES ASIGNATURAS (CODIGO);

ALTER TABLE IMPARTIR ADD CONSTRAINT FK_IMPARTIR_ASIG FOREIGN KEY (ASIGNATURA) REFERENCES ASIGNATURAS (CODIGO);
ALTER TABLE IMPARTIR ADD CONSTRAINT FK_IMPARTIR_PROFE FOREIGN KEY (PROFESOR) REFERENCES PROFESORES (ID);

ALTER TABLE INVESTIGADORES ADD CONSTRAINT FK_DIRECTOR_PROFE FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESORES (ID);

ALTER TABLE MATRICULAR ADD CONSTRAINT FK_MATRICULA_ALUMNO FOREIGN KEY (ALUMNO) REFERENCES ALUMNOS (DNI); 
ALTER TABLE MATRICULAR ADD CONSTRAINT FK_MATRICULA_ASIGNATURA FOREIGN KEY (ASIGNATURA) REFERENCES ASIGNATURAS (CODIGO);

ALTER TABLE MUNICIPIO ADD CONSTRAINT MUNICIPIO_FK1 FOREIGN KEY (CPRO) REFERENCES PROVINCIA (CODIGO);

ALTER TABLE PRERREQUISITOS ADD CONSTRAINT FK_PRE_ASIG FOREIGN KEY (ASIGNATURA) REFERENCES ASIGNATURAS (CODIGO);
ALTER TABLE PRERREQUISITOS ADD CONSTRAINT FK_PRE_ASIG_PRE FOREIGN KEY (PRERREQUISITO) REFERENCES ASIGNATURAS (CODIGO);

ALTER TABLE PROFESORES ADD CONSTRAINT FK_DIRECTOR_TESIS FOREIGN KEY (DIRECTOR_TESIS) REFERENCES PROFESORES (ID);
ALTER TABLE PROFESORES ADD CONSTRAINT FK_PROFESOR_DEPAR FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTOS (CODIGO);